---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
--- # Prometheus persistent data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  claimRef:
    namespace: monitoring
    name: data-prometheus-0 # <prefix>-<sts_pod_name> postfix -0 is necessary cause of sts
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/prometheus_data # specify your path on the node's fs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 'worker1-kvm' # specify your node hostname
