{
 "title": "pod metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "echo-server ns CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "millicores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"echo-server\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "echo-server ns MEMORY load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"echo-server\",container_label_io_kubernetes_container_name!=\"POD\"} / 1024 ^ 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod RESTARTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"echo-server\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod INFO",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"echo-server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}